// ── Canonical genre list ──────────────────────────────────────────────────────
// Single source of truth used by SetupScreen, EditProfileScreen, CatalogScreen,
// BookDetailScreen, and AI prompts. Keys match GENRE_DB_GROUPS exactly.
// Ordered by popularity (most-used first).
export const GENRES_META = [
  { key: 'fiction',     en: 'Fiction',      he: 'סיפורת',         icon: 'book-outline',          color: '#2563eb', bg: '#eff6ff' },
  { key: 'romance',     en: 'Romance',      he: 'רומנטיקה',       icon: 'heart-outline',         color: '#db2777', bg: '#fce7f3' },
  { key: 'mystery',     en: 'Mystery',      he: 'מתח ומסתורין',  icon: 'search-outline',        color: '#6d28d9', bg: '#ede9fe' },
  { key: 'fantasy',     en: 'Fantasy',      he: 'פנטזיה',         icon: 'sparkles-outline',      color: '#7c3aed', bg: '#f5f3ff' },
  { key: 'young-adult', en: 'Young Adult',  he: 'נוער',           icon: 'star-outline',          color: '#d97706', bg: '#fef3c7' },
  { key: 'sci-fi',      en: 'Sci-Fi',       he: 'מדע בדיוני',    icon: 'planet-outline',        color: '#0891b2', bg: '#cffafe' },
  { key: 'children',    en: "Children's",   he: 'ספרי ילדים',    icon: 'happy-outline',         color: '#f59e0b', bg: '#fef9c3' },
  { key: 'biography',   en: 'Biography',    he: 'ביוגרפיה',      icon: 'person-outline',        color: '#2563eb', bg: '#eff6ff' },
  { key: 'self-help',   en: 'Self-Help',    he: 'עזרה עצמית',   icon: 'fitness-outline',       color: '#059669', bg: '#d1fae5' },
  { key: 'business',    en: 'Business',     he: 'עסקים',          icon: 'briefcase-outline',     color: '#0f766e', bg: '#ccfbf1' },
  { key: 'historical',  en: 'Historical',   he: 'סיפורת היסטורית', icon: 'hourglass-outline',   color: '#92400e', bg: '#fef3c7' },
  { key: 'adventure',   en: 'Adventure',    he: 'הרפתקאות',      icon: 'compass-outline',       color: '#059669', bg: '#d1fae5' },
  { key: 'psychology',  en: 'Psychology',   he: 'פסיכולוגיה',    icon: 'bulb-outline',          color: '#7c3aed', bg: '#f5f3ff' },
  { key: 'health',      en: 'Health',       he: 'בריאות',         icon: 'medkit-outline',        color: '#dc2626', bg: '#fee2e2' },
  { key: 'cooking',     en: 'Cooking',      he: 'בישול',          icon: 'restaurant-outline',    color: '#d97706', bg: '#fef3c7' },
  { key: 'history',     en: 'History',      he: 'היסטוריה',      icon: 'time-outline',          color: '#92400e', bg: '#fef3c7' },
  { key: 'horror',      en: 'Horror',       he: 'אימה',           icon: 'warning-outline',       color: '#dc2626', bg: '#fee2e2' },
  { key: 'science',     en: 'Science',      he: 'מדע וטבע',      icon: 'flask-outline',         color: '#0891b2', bg: '#cffafe' },
  { key: 'art',         en: 'Art',          he: 'אמנות',          icon: 'color-palette-outline', color: '#db2777', bg: '#fce7f3' },
  { key: 'travel',      en: 'Travel',       he: 'טיולים',         icon: 'airplane-outline',      color: '#0f766e', bg: '#ccfbf1' },
  { key: 'philosophy',  en: 'Philosophy',   he: 'פילוסופיה',     icon: 'infinite-outline',      color: '#6d28d9', bg: '#ede9fe' },
  { key: 'religion',    en: 'Religion',     he: 'דת ורוחניות',  icon: 'prism-outline',         color: '#92400e', bg: '#fef3c7' },
  { key: 'comics',      en: 'Comics',       he: 'קומיקס',        icon: 'layers-outline',        color: '#dc2626', bg: '#fee2e2' },
  { key: 'poetry',      en: 'Poetry',       he: 'שירה',           icon: 'pencil-outline',        color: '#6d28d9', bg: '#ede9fe' },
  { key: 'humor',       en: 'Humor',        he: 'הומור',          icon: 'chatbubbles-outline',   color: '#2563eb', bg: '#eff6ff' },
] as const;

// Convenience lookup: key → { en, he } — use instead of local GENRE_LABELS maps
export const GENRE_LABEL_MAP: Record<string, { en: string; he: string }> =
  Object.fromEntries(GENRES_META.map(g => [g.key, { en: g.en, he: g.he }]));

export const BOOK_CATEGORIES = [
  { value: 'reading', label: 'Reading Books', labelHe: 'ספרי קריאה', icon: '📖' },
  { value: 'study', label: 'Study Books', labelHe: 'ספרי לימוד', icon: '🎓' },
  { value: 'children', label: "Children's Books", labelHe: 'ספרי ילדים', icon: '👶' },
  { value: 'professional', label: 'Professional Books', labelHe: 'ספרים מקצועיים', icon: '💼' },
  { value: 'reference', label: 'Reference Books', labelHe: 'ספרי עיון', icon: '📚' },
  { value: 'magazines', label: 'Magazines & Comics', labelHe: 'מגזינים וקומיקס', icon: '📰' },
] as const;

export const BOOK_GENRES = [
  // Fiction Genres
  { value: 'fiction', label: 'Fiction', labelHe: 'סיפורת' },
  { value: 'mystery', label: 'Mystery & Thriller', labelHe: 'מתח ומסתורין' },
  { value: 'romance', label: 'Romance', labelHe: 'רומנטיקה' },
  { value: 'sci-fi', label: 'Science Fiction', labelHe: 'מדע בדיוני' },
  { value: 'fantasy', label: 'Fantasy', labelHe: 'פנטזיה' },
  { value: 'horror', label: 'Horror', labelHe: 'אימה' },
  { value: 'historical', label: 'Historical Fiction', labelHe: 'סיפורת היסטורית' },
  { value: 'adventure', label: 'Adventure', labelHe: 'הרפתקאות' },
  { value: 'young-adult', label: 'Young Adult', labelHe: 'נוער' },

  // Non-Fiction Genres
  { value: 'children', label: "Children's Books", labelHe: 'ספרי ילדים' },
  { value: 'biography', label: 'Biography', labelHe: 'ביוגרפיה' },
  { value: 'self-help', label: 'Self-Help', labelHe: 'עזרה עצמית' },
  { value: 'business', label: 'Business & Economics', labelHe: 'עסקים וכלכלה' },
  { value: 'psychology', label: 'Psychology', labelHe: 'פסיכולוגיה' },
  { value: 'philosophy', label: 'Philosophy', labelHe: 'פילוסופיה' },
  { value: 'history', label: 'History', labelHe: 'היסטוריה' },
  { value: 'science', label: 'Science & Nature', labelHe: 'מדע וטבע' },
  { value: 'health', label: 'Health & Wellness', labelHe: 'בריאות' },
  { value: 'cooking', label: 'Cooking', labelHe: 'בישול' },
  { value: 'art', label: 'Art & Photography', labelHe: 'אמנות וצילום' },
  { value: 'travel', label: 'Travel', labelHe: 'טיולים' },
  { value: 'religion', label: 'Religion & Spirituality', labelHe: 'דת ורוחניות' },
  { value: 'poetry', label: 'Poetry', labelHe: 'שירה' },
  { value: 'humor', label: 'Humor', labelHe: 'הומור' },
  { value: 'comics', label: 'Comics & Graphic Novels', labelHe: 'קומיקס ורומנים גרפיים' },
] as const;

export const BOOK_CONDITIONS = [
  { value: 'new', label: 'New', labelHe: 'חדש' },
  { value: 'like_new', label: 'Like New', labelHe: 'כמו חדש' },
  { value: 'good', label: 'Good', labelHe: 'טוב' },
  { value: 'fair', label: 'Fair', labelHe: 'סביר' },
] as const;

export const LISTING_TYPES = [
  { value: 'free', label: 'Free', labelHe: 'חינם', icon: '🎁' },
  { value: 'sale', label: 'For Sale', labelHe: 'למכירה', icon: '💰' },
  { value: 'trade', label: 'Trade', labelHe: 'לחליפין', icon: '🔄' },
] as const;

// Popular cities shown as quick-select chips
export const POPULAR_CITIES = [
  'תל אביב',
  'ירושלים',
  'חיפה',
  'באר שבע',
  'ראשון לציון',
  'פתח תקווה',
  'נתניה',
  'אשדוד',
] as const;

// Maps broad mobile filter keys → all matching DB sub-genre values
export const GENRE_DB_GROUPS: Record<string, string[]> = {
  'fiction':    ['fiction', 'literary_fiction', 'drama', 'short_stories'],
  'mystery':    ['mystery', 'thriller', 'crime_detective'],
  'romance':    ['romance', 'teen_romance'],
  'sci-fi':     ['sci-fi', 'science_fiction'],
  'fantasy':    ['fantasy', 'teen_fantasy'],
  'horror':     ['horror'],
  'historical': ['historical', 'historical_fiction'],
  'adventure':  ['adventure'],
  'young-adult':['young-adult', 'teen_fiction', 'teen_fantasy', 'teen_romance', 'teen_science_fiction'],
  'children':   ['children', 'picture_books', 'early_reading', 'chapter_books', 'educational_kids', 'comics_kids', 'bedtime_stories'],
  'biography':  ['biography', 'biography_memoir'],
  'self-help':  ['self-help', 'self_improvement', 'motivation', 'mindfulness', 'productivity'],
  'business':   ['business', 'business_management', 'finance', 'career_development', 'economics'],
  'psychology': ['psychology', 'mental_health'],
  'philosophy': ['philosophy'],
  'history':    ['history'],
  'science':    ['science', 'science_fiction'],
  'health':     ['health', 'health_wellness', 'nutrition', 'fitness'],
  'cooking':    ['cooking', 'cooking_baking'],
  'art':        ['art', 'art_design', 'photography'],
  'travel':     ['travel', 'travel_writing', 'travel_guide'],
  'religion':   ['religion', 'spirituality', 'religious_text', 'commentary_interpretation'],
  'poetry':     ['poetry'],
  'humor':      ['humor'],
  'comics':     ['comics', 'comics_kids', 'graphic_novel_comics'],
};

// Reverse lookup: maps any DB sub-genre value → its parent's {en, he} label.
// Use this when rendering genres from book.genres, which may contain sub-values
// like 'historical_fiction', 'educational_kids', 'business_management', etc.
export const DB_VALUE_TO_LABEL: Record<string, { en: string; he: string }> =
  Object.fromEntries(
    Object.entries(GENRE_DB_GROUPS).flatMap(([parentKey, dbValues]) => {
      const label = GENRE_LABEL_MAP[parentKey];
      return label ? dbValues.map(v => [v, label]) : [];
    })
  );

// Approximate city center coordinates for distance-sort fallback
export const CITY_COORDS: Record<string, { lat: number; lng: number }> = {
  'תל אביב':             { lat: 32.0853, lng: 34.7818 },
  'ירושלים':             { lat: 31.7683, lng: 35.2137 },
  'חיפה':                { lat: 32.7940, lng: 34.9896 },
  'באר שבע':             { lat: 31.2518, lng: 34.7915 },
  'ראשון לציון':         { lat: 31.9730, lng: 34.7925 },
  'פתח תקווה':           { lat: 32.0840, lng: 34.8878 },
  'נתניה':               { lat: 32.3215, lng: 34.8532 },
  'אשדוד':              { lat: 31.8040, lng: 34.6550 },
  'חולון':               { lat: 32.0114, lng: 34.7739 },
  'בני ברק':             { lat: 32.0841, lng: 34.8337 },
  'רמת גן':              { lat: 32.0679, lng: 34.8235 },
  'אשקלון':              { lat: 31.6688, lng: 34.5742 },
  'רחובות':              { lat: 31.8928, lng: 34.8113 },
  'בת ים':               { lat: 32.0165, lng: 34.7506 },
  'כפר סבא':             { lat: 32.1780, lng: 34.9065 },
  'הרצליה':              { lat: 32.1663, lng: 34.8437 },
  'חדרה':                { lat: 32.4358, lng: 34.9192 },
  'מודיעין-מכבים-רעות':  { lat: 31.8983, lng: 35.0108 },
  'נהריה':               { lat: 33.0070, lng: 35.0981 },
  'לוד':                 { lat: 31.9516, lng: 34.8966 },
  'רמלה':                { lat: 31.9298, lng: 34.8706 },
  'נס ציונה':            { lat: 31.9302, lng: 34.7987 },
  'ראש העין':            { lat: 32.0958, lng: 34.9575 },
  'גבעתיים':             { lat: 32.0700, lng: 34.8125 },
  'עכו':                 { lat: 32.9282, lng: 35.0818 },
  'אילת':                { lat: 29.5577, lng: 34.9519 },
  'טבריה':               { lat: 32.7940, lng: 35.5321 },
  'צפת':                 { lat: 32.9646, lng: 35.4960 },
  'קריית גת':            { lat: 31.6115, lng: 34.7651 },
  'קריית שמונה':         { lat: 33.2074, lng: 35.5695 },
  'דימונה':              { lat: 31.0697, lng: 35.0326 },
  'ערד':                 { lat: 31.2588, lng: 35.2134 },
  'יבנה':                { lat: 31.8769, lng: 34.7421 },
  'קריית אתא':           { lat: 32.8068, lng: 35.1109 },
  'קריית ביאליק':        { lat: 32.8342, lng: 35.0790 },
  'קריית מוצקין':        { lat: 32.8378, lng: 35.0773 },
  'קריית ים':            { lat: 32.8527, lng: 35.0625 },
  'קריית אונו':          { lat: 32.0611, lng: 34.8573 },
  'הוד השרון':           { lat: 32.1503, lng: 34.8966 },
  'רעננה':               { lat: 32.1840, lng: 34.8705 },
  'רמת השרון':           { lat: 32.1469, lng: 34.8401 },
  'כרמיאל':              { lat: 32.9144, lng: 35.2978 },
  'נצרת':                { lat: 32.6996, lng: 35.3035 },
  'עפולה':               { lat: 32.6078, lng: 35.2897 },
  'שדרות':               { lat: 31.5253, lng: 34.5970 },
  'בית שמש':             { lat: 31.7471, lng: 34.9872 },
  'אריאל':               { lat: 32.1053, lng: 35.1714 },
};

// Full city list (Hebrew) — cities, towns, kibbutzim, moshavim, Arab localities, settlements
export const CITIES = [
  // === ערים גדולות ===
  'תל אביב',
  'ירושלים',
  'חיפה',
  'באר שבע',
  'ראשון לציון',
  'פתח תקווה',
  'נתניה',
  'אשדוד',
  'חולון',
  'בני ברק',
  'רמת גן',
  'אשקלון',
  'רחובות',
  'בת ים',
  'כפר סבא',
  'הרצליה',
  'חדרה',
  'מודיעין-מכבים-רעות',
  'נהריה',
  'לוד',
  'רמלה',
  'נס ציונה',
  'ראש העין',
  'גבעתיים',
  'עכו',
  'אילת',
  'טבריה',
  'צפת',
  'קריית גת',
  'קריית שמונה',
  'דימונה',
  'ערד',
  'יבנה',
  'קריית אתא',
  'קריית ביאליק',
  'קריית מוצקין',
  'קריית ים',
  'קריית אונו',
  'הוד השרון',
  'יהוד-מונוסון',
  'אור יהודה',
  'גדרה',
  'מעלה אדומים',
  'בית שמש',
  'אריאל',
  'רעננה',
  'רמת השרון',
  'מודיעין עילית',
  'כרמיאל',
  'אלעד',
  'בית שאן',
  'טירת כרמל',
  'שדרות',
  'עפולה',
  'רהט',
  'קריית מלאכי',
  'מגדל העמק',
  'נוף הגליל',
  'נצרת',
  'סחנין',
  'אופקים',
  'אור עקיבא',
  'זכרון יעקב',
  'נתיבות',
  'קצרין',
  'שוהם',
  'נשר',
  'חריש',
  'ביתר עילית',
  'מעלות-תרשיחא',
  'פרדס חנה-כרכור',
  // === ערים ועיירות נוספות ===
  'גבעת שמואל',
  'גן יבנה',
  'אבן יהודה',
  'כפר יונה',
  'יוקנעם עילית',
  'מצפה רמון',
  'ירוחם',
  'מבשרת ציון',
  'עומר',
  'בנימינה-גבעת עדה',
  'עתלית',
  'קיסריה',
  'ראש פינה',
  'חצור הגלילית',
  'יסוד המעלה',
  'כפר תבור',
  'מגדל',
  'שדה בוקר',
  'נבטים',
  'גבעת ברנר',
  'גבעת זאב',
  'כפר ויתקין',
  'גן חיים',
  'בית שערים',
  'יפו',
  'יפיע',
  // === ישובים ערביים ===
  'אום אל-פחם',
  'טייבה',
  'טירה',
  'כפר קאסם',
  'שפרעם',
  'ג\'לג\'וליה',
  'ג\'ת',
  'ריינה',
  'כפר כנא',
  'עראבה',
  'ערערה',
  'כפר קרע',
  'עוספיה',
  'כפר יאסיף',
  'דאלית אל-כרמל',
  'ג\'דיידה-מכר',
  'כאבול',
  'בועינה-נוג\'ידאת',
  'עיילבון',
  'ג\'יש',
  'כסרא-סמיע',
  'חורפיש',
  'פסוטה',
  'מעיליא',
  'כפר מנדא',
  'טמרה',
  'באקה אל-גרביה',
  'אבו גוש',
  'דיר חנא',
  'נחף',
  'דיר אל-אסד',
  'עין מאהל',
  'ריחאנייה',
  'שגור',
  'ראמה',
  'כפר כמא',
  'ברטעה-שחאב',
  'עין קינייה',
  'בסמת טבעון',
  'ג\'את',
  'מג\'ד אל-כרום',
  'עספיא',
  'ג\'לבינה',
  // === ישובים בגדה המערבית ===
  'קרית ארבע',
  'אפרת',
  'קרני שומרון',
  'אלפי מנשה',
  'בית אריה-עופרים',
  'אלון שבות',
  'קדומים',
  'אלון מורה',
  // === קיבוצים ומושבים ===
  'לוחמי הגטאות',
  'שדות ים',
  'מעגן מיכאל',
  'יגור',
  'כפר מסריק',
  'נהלל',
  'כפר יחזקאל',
  'גן שמואל',
  'מעיין צבי',
  'גינוסר',
  'כינרת',
  'כפר בלום',
  'שמיר',
  'מנרה',
  'כפר הנשיא',
  'עין גדי',
  'ניר עוז',
  'עין יהב',
  'נאות מרדכי',
  'כפר נהר הירדן',
  'בית אלפא',
  'עין חרוד',
  'גבע',
  'כפר גלים',
  'שדות מיכה',
  'רמות נפתלי',
  'מעלה גמלא',
  // === גולן ===
  'מגדל שמס',
  'מסעדה',
  'בוקעתא',
  'עין קנייה',
  'אל-רום',
  'נווה אטי"ב',
  'קצרין (קריית)',
] as const;
